coverage:
  status:
    project:
      default: false
      warning:
        target: 100%
        informational: true
      minimum:
        target: 90%
        informational: false
    patch:
      default:
        informational: true
comment:
  layout: "reach, diff, files"
  require_changes: true
