name: body-template

on:
  pull_request:
    types: [opened, edited, reopened]
  issues:
    types: [opened, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pr-body:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: A PR body must conform to pull_request_template.md
      env:
        PR_BODY: ${{ github.event.pull_request.body }}
      run: ./scripts/check-body-template.sh pr

  issue-body:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: An issue body must conform to ISSUE_TEMPLATE/issue.md
      env:
        ISSUE_BODY: ${{ github.event.issue.body }}
        ISSUE_CREATED_AT: ${{ github.event.issue.created_at }}
      run: ./scripts/check-body-template.sh issue
